name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer PHP (si besoin pour Composer)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # ou la version que tu utilises

      # 3️⃣ Installer Composer (si tu utilises Composer)
      #- name: Install Composer dependencies
       # run: composer install --no-progress --prefer-dist
        #working-directory: ./ # mettre le dossier où se trouve ton composer.json

      # 4️⃣ Se connecter à Docker Hub avec les secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t josef90/grade-management:latest .

      # 6️⃣ Push de l'image sur Docker Hub
      - name: Push Docker image
        run: |
          docker push josef90/grade-management:latest

