name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer PHP + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # 3. Exécuter PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox --log-junit test-reports/result.xml

      # 4. Sauvegarder rapport de test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-report
          path: test-reports/

      # 5. Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build de l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/grade-management:latest .

      # 7. Push vers Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/grade-management:latest


      # 8️⃣ Déploiement automatique sur serveur distant (SSH)
      #- name: Deploy to Server
       # uses: appleboy/ssh-action@v0.1.6
        #with:
         # host: ${{ secrets.SERVER_IP }}
          #username: ${{ secrets.SERVER_USER }}
          #key: ${{ secrets.SERVER_SSH_KEY }}
          #script: |
           # docker pull ${{ secrets.DOCKER_USERNAME }}/grade-management:latest
            #docker-compose up -d
